name: Analyze Audio
on:
  workflow_dispatch:
    inputs:
      filePath:
        description: 'full file path (including name + extension) for file to analyze in b2 storage'
        required: true
      bucketName:
        description: 'name of bucket in b2 storage containing the file to analyze'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        # python -m pip install
        # pip install flake8 pytest
        pip install 'requests==2.31.0'
        pip install 'librosa==0.10.1'
        pip install numpy
        pip install 'moviepy==1.0.3'
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: mod librosa dependency
      run: |
        cd /opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/librosa
        if [ ! -f beat.py]; then
          echo "Error: beat.py does not exist."
          exit 1
        fi
        tempfile=$(mktemp)
        sed 's/hann(/windows.hann(/g' beat.py > "$tempfile"
        mv "$tempfile" beat.py
        echo "Replacement complete."
        
    - name: Analyze Audio
      run: |
        echo Downloading File...
        output=$(python FileDownload.py ${{ secrets.BB_AUTH_A }} ${{ secrets.BB_AUTH_B }} ${{ github.event.inputs.filePath }} ${{ github.event.inputs.bucketName }})
        outFile=$(echo "$output" | tail -n 1)
        echo $outFile

        echo Converting File...
        convertedAll=$(python FileConversion.py $outFile)
        convertedFile=$(echo "$convertedAll" | tail -n 1)
        echo $convertedFile

        echo Analyzing File...
        python AudioAnalysis.py $convertedFile
